# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import models.uc_api.grpc.service_control_pb2 as service__control__pb2


class ServiceControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/protei.uc.api.ServiceControl/Check',
                request_serializer=service__control__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=service__control__pb2.HealthCheckResponse.FromString,
                )
        self.Watch = channel.unary_stream(
                '/protei.uc.api.ServiceControl/Watch',
                request_serializer=service__control__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=service__control__pb2.HealthCheckResponse.FromString,
                )
        self.SrvUpdate = channel.unary_unary(
                '/protei.uc.api.ServiceControl/SrvUpdate',
                request_serializer=service__control__pb2.SrvRecordUpdateRequest.SerializeToString,
                response_deserializer=service__control__pb2.SrvRecordUpdateResponse.FromString,
                )


class ServiceControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SrvUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=service__control__pb2.HealthCheckRequest.FromString,
                    response_serializer=service__control__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=service__control__pb2.HealthCheckRequest.FromString,
                    response_serializer=service__control__pb2.HealthCheckResponse.SerializeToString,
            ),
            'SrvUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SrvUpdate,
                    request_deserializer=service__control__pb2.SrvRecordUpdateRequest.FromString,
                    response_serializer=service__control__pb2.SrvRecordUpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protei.uc.api.ServiceControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServiceControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protei.uc.api.ServiceControl/Check',
            service__control__pb2.HealthCheckRequest.SerializeToString,
            service__control__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/protei.uc.api.ServiceControl/Watch',
            service__control__pb2.HealthCheckRequest.SerializeToString,
            service__control__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SrvUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protei.uc.api.ServiceControl/SrvUpdate',
            service__control__pb2.SrvRecordUpdateRequest.SerializeToString,
            service__control__pb2.SrvRecordUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
