# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_control.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15service_control.proto\x12\rprotei.uc.api\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xaa\x01\n\x13HealthCheckResponse\x12@\n\x06status\x18\x01 \x01(\x0e\x32\x30.protei.uc.api.HealthCheckResponse.ServingStatus\x12\x13\n\x0binformation\x18\x02 \x01(\t\"<\n\rServingStatus\x12\r\n\tNOT_FOUND\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\"(\n\x16SrvRecordUpdateRequest\x12\x0e\n\x06record\x18\x01 \x01(\t\"\x19\n\x17SrvRecordUpdateResponse2\x8e\x02\n\x0eServiceControl\x12N\n\x05\x43heck\x12!.protei.uc.api.HealthCheckRequest\x1a\".protei.uc.api.HealthCheckResponse\x12P\n\x05Watch\x12!.protei.uc.api.HealthCheckRequest\x1a\".protei.uc.api.HealthCheckResponse0\x01\x12Z\n\tSrvUpdate\x12%.protei.uc.api.SrvRecordUpdateRequest\x1a&.protei.uc.api.SrvRecordUpdateResponseB\x0eZ\x0c\x61pi/grpc;apib\x06proto3')



_HEALTHCHECKREQUEST = DESCRIPTOR.message_types_by_name['HealthCheckRequest']
_HEALTHCHECKRESPONSE = DESCRIPTOR.message_types_by_name['HealthCheckResponse']
_SRVRECORDUPDATEREQUEST = DESCRIPTOR.message_types_by_name['SrvRecordUpdateRequest']
_SRVRECORDUPDATERESPONSE = DESCRIPTOR.message_types_by_name['SrvRecordUpdateResponse']
_HEALTHCHECKRESPONSE_SERVINGSTATUS = _HEALTHCHECKRESPONSE.enum_types_by_name['ServingStatus']
HealthCheckRequest = _reflection.GeneratedProtocolMessageType('HealthCheckRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKREQUEST,
  '__module__' : 'service_control_pb2'
  # @@protoc_insertion_point(class_scope:protei.uc.api.HealthCheckRequest)
  })
_sym_db.RegisterMessage(HealthCheckRequest)

HealthCheckResponse = _reflection.GeneratedProtocolMessageType('HealthCheckResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKRESPONSE,
  '__module__' : 'service_control_pb2'
  # @@protoc_insertion_point(class_scope:protei.uc.api.HealthCheckResponse)
  })
_sym_db.RegisterMessage(HealthCheckResponse)

SrvRecordUpdateRequest = _reflection.GeneratedProtocolMessageType('SrvRecordUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _SRVRECORDUPDATEREQUEST,
  '__module__' : 'service_control_pb2'
  # @@protoc_insertion_point(class_scope:protei.uc.api.SrvRecordUpdateRequest)
  })
_sym_db.RegisterMessage(SrvRecordUpdateRequest)

SrvRecordUpdateResponse = _reflection.GeneratedProtocolMessageType('SrvRecordUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _SRVRECORDUPDATERESPONSE,
  '__module__' : 'service_control_pb2'
  # @@protoc_insertion_point(class_scope:protei.uc.api.SrvRecordUpdateResponse)
  })
_sym_db.RegisterMessage(SrvRecordUpdateResponse)

_SERVICECONTROL = DESCRIPTOR.services_by_name['ServiceControl']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\014api/grpc;api'
  _HEALTHCHECKREQUEST._serialized_start=40
  _HEALTHCHECKREQUEST._serialized_end=77
  _HEALTHCHECKRESPONSE._serialized_start=80
  _HEALTHCHECKRESPONSE._serialized_end=250
  _HEALTHCHECKRESPONSE_SERVINGSTATUS._serialized_start=190
  _HEALTHCHECKRESPONSE_SERVINGSTATUS._serialized_end=250
  _SRVRECORDUPDATEREQUEST._serialized_start=252
  _SRVRECORDUPDATEREQUEST._serialized_end=292
  _SRVRECORDUPDATERESPONSE._serialized_start=294
  _SRVRECORDUPDATERESPONSE._serialized_end=319
  _SERVICECONTROL._serialized_start=322
  _SERVICECONTROL._serialized_end=592
# @@protoc_insertion_point(module_scope)
